CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
uName VARCHAR(10) NOT NULL,
uPwd VARCHAR(20) NOT NULL,
uEmail VARCHAR(20) NOT NULL

)

INSERT INTO users VALUES(NULL,'小王','123456','123456@163.com')

SELECT * FROM users
DELETE * FROM users WHERE 